# Local Job Scheduler Configuration
# This file defines jobs for local Docker development

global:
  defaultTimeout: 10000
  defaultRetries: 3
  defaultHeaders:
    Content-Type: application/json

jobs:
  # KPI Afternoon Report - Weekdays at 1:01 PM
  - name: kpi-afternoon-report-local
    schedule: "0 1 13 * * 1-5"  # Weekdays at 1:01 PM (Monday-Friday)
    url: "http://slack-kpi-service-aircall-slack-agent-1:6000/report/afternoon"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app-local"
      Content-Type: application/json
    timeout: 15000
    retries: 2
    enabled: true
    description: "KPI afternoon report generation - Weekdays at 1:01 PM - calling actual KPI service"

  # KPI Evening Report - Weekdays at 7:00 PM
  - name: kpi-evening-report-local
    schedule: "0 0 19 * * 1-5"  # Weekdays at 7:00 PM (Monday-Friday)
    url: "http://slack-kpi-service-aircall-slack-agent-1:6000/report/night"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app-local"
      Content-Type: application/json
    timeout: 15000
    retries: 2
    enabled: true
    description: "KPI evening report generation - Weekdays at 7:00 PM - calling actual KPI service"

  # Health check job for Slack-KPI-Service - Local version
  - name: kpi-service-health-check-local
    schedule: "0 */1 * * * *"  # Every minute for local testing
    url: "http://test-api-server-local:8080/health"
    method: GET
    timeout: 5000
    retries: 2
    enabled: false
    description: "Local health check for test API server (every minute)"

  # Test job that runs every 30 seconds (for debugging)
  - name: test-kpi-endpoint-local
    schedule: "*/30 * * * * *"  # Every 30 seconds for local testing
    url: "http://slack-kpi-service-aircall-slack-agent-1:8080/report/afternoon"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "test-job-local"
      Content-Type: application/json
    data:
      test_mode: true
      timestamp: "${NOW}"
      action: "test_kpi_endpoint_local"
      environment: "local"
    timeout: 5000
    retries: 1
    enabled: false
    description: "Local test job to verify test API connectivity (every 30 seconds)"

  # Test API server health check (if running locally)
  - name: test-api-health-check
    schedule: "0 */2 * * * *"  # Every 2 minutes
    url: "http://slack-kpi-service-aircall-slack-agent-1:8080/health"
    method: GET
    timeout: 5000
    retries: 2
    enabled: false  # Enabled since we're using test-api for local testing
    description: "Health check for local test API server"
