# Job Scheduler Configuration
# This file defines jobs that will be executed by the scheduler

global:
  defaultTimeout: 10000
  defaultRetries: 3
  defaultHeaders:
    Content-Type: application/json

jobs:
  # KPI Afternoon Report - Weekdays at 1:01 PM
  - name: kpi-afternoon-report
    schedule: "0 1 13 * * 1-5"  # Weekdays at 1:01 PM
    url: "http://test-api-server:8080/report/afternoon"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app"
      Content-Type: "application/json"
    timeout: 15000
    retries: 2
    enabled: true
    description: "KPI afternoon report generation"

  # KPI Evening Report - Weekdays at 6:30 PM
  - name: kpi-evening-report
    schedule: "0 30 18 * * 1-5"  # Weekdays at 6:30 PM
    url: "http://test-api-server:8080/report/evening"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app"
      Content-Type: "application/json"
    timeout: 15000
    retries: 2
    enabled: true
    description: "KPI evening report generation at 6:30 PM"

  # Health check job
  - name: health-check-test
    schedule: "0 */1 * * * *"  # Every minute
    url: "http://test-api-server:8080/health"
    method: GET
    timeout: 5000
    retries: 2
    enabled: false
    description: "Health check for test API server" 