# Job Scheduler Configuration
# This file defines jobs that will be executed by the scheduler

global:
  defaultTimeout: 10000
  defaultRetries: 3
  defaultHeaders:
    Content-Type: application/json

jobs:
  # KPI Afternoon Report - Weekdays at 1:01 PM
  - name: kpi-afternoon-report
    schedule: "1 13 * * 1-5"  # Weekdays at 1:01 PM (CST)
    url: "https://slack-kpi-service-dbf2f7d60f2e.herokuapp.com/report/afternoon"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app"
      Content-Type: "application/json"
    timeout: 15000
    retries: 2
    enabled: true
    description: "KPI afternoon report generation"

  # KPI Evening Report - Weekdays at 6:30 PM
  - name: kpi-evening-report
    schedule: "30 18 * * 1-5"  # Weekdays at 6:30 PM (CST)
    url: "https://slack-kpi-service-dbf2f7d60f2e.herokuapp.com/report/night"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app"
      Content-Type: "application/json"
    timeout: 15000
    retries: 2
    enabled: true
    description: "KPI evening report generation at 6:30 PM (using afternoon endpoint)"

  # Health check job
  - name: health-check-test
    schedule: "*/1 * * * *"  # Every minute
    url: "http://test-api-server:8080/health"
    method: GET
    timeout: 5000
    retries: 2
    enabled: false
    description: "Health check for test API server"

  # Test job that runs every minute
  - name: test-job-minute
    schedule: "* * * * *"  # Every minute
    url: "https://slack-kpi-service-dbf2f7d60f2e.herokuapp.com/report/afternoon"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "test-job"
      Content-Type: "application/json"
    timeout: 5000
    retries: 1
    enabled: false
    description: "Test job that runs every minute to verify scheduler and endpoint" 