# Job Scheduler Configuration
# This file defines jobs that will be executed by the scheduler

global:
  defaultTimeout: 10000
  defaultRetries: 3
  defaultHeaders:
    Content-Type: application/json

jobs:
  # KPI Afternoon Report - Weekdays at 1:01 PM
  - name: kpi-afternoon-report
    schedule: "1 13 * * 1-5"  # Weekdays at 1:01 PM (CST)
    url: "https://slack-kpi-service-dbf2f7d60f2e.herokuapp.com/report/afternoon"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app"
      Content-Type: "application/json"
    timeout: 30000
    retries: 2
    enabled: false
    description: "KPI afternoon report generation"

  # KPI Evening Report - Weekdays at 6:30 PM
  - name: kpi-evening-report
    schedule: "30 18 * * 1-5"  # Weekdays at 6:30 PM (CST)
    url: "https://slack-kpi-service-dbf2f7d60f2e.herokuapp.com/report/night"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app"
      Content-Type: "application/json"
    timeout: 45000
    retries: 3
    enabled: true
    description: "KPI evening report generation at 6:30 PM"

  # KPI Evening Report Backup - Weekdays at 6:35 PM (5 minutes later)
  - name: kpi-evening-report-backup
    schedule: "35 18 * * 1-5"  # Weekdays at 6:35 PM (CST) - Backup
    url: "https://slack-kpi-service-dbf2f7d60f2e.herokuapp.com/report/night"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app-backup"
      Content-Type: "application/json"
    timeout: 45000
    retries: 3
    enabled: true
    description: "KPI evening report backup at 6:35 PM (5 minutes after primary)"
    dependsOn:
      job: kpi-evening-report
      windowMinutes: 20  # look back 20 minutes to confirm primary ran and succeeded
      condition: not_ran_or_failed

  # KPI Weekly Average Report - Fridays at 6:45 PM (end of week)
  - name: kpi-weekly-avg-report
    schedule: "45 18 * * 5"  # Fridays at 6:45 PM (CST) - End of week
    url: "https://slack-kpi-service-dbf2f7d60f2e.herokuapp.com/report/weekly-avg"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "kpi-app"
      Content-Type: "application/json"
    data:
      weekRange: "current"  # Current week Monday-Friday
    timeout: 45000
    retries: 3
    enabled: true
    description: "KPI weekly average report for current week (Monday-Friday) at end of week"

  # Health check job
  - name: health-check-test
    schedule: "*/1 * * * *"  # Every minute
    url: "http://test-api-server:8080/health"
    method: GET
    timeout: 5000
    retries: 2
    enabled: false
    description: "Health check for test API server"

  # Test job that runs every minute
  - name: test-job-minute
    schedule: "* * * * *"  # Every minute
    url: "https://slack-kpi-service-dbf2f7d60f2e.herokuapp.com/report/afternoon"
    method: POST
    headers:
      Authorization: "Bearer ${JWT_TOKEN}"
      X-Custom-Header: "test-job"
      Content-Type: "application/json"
    timeout: 5000
    retries: 1
    enabled: false
    description: "Test job that runs every minute to verify scheduler and endpoint" 