name: Deploy to GKE

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  REGISTRY: gcr.io
  IMAGE_NAME: job-scheduler

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Test Docker build
      run: docker build -t $IMAGE_NAME .

  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker
      
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
          --zone ${{ env.GKE_ZONE }} \
          --project ${{ env.PROJECT_ID }}
          
    - name: Update Kubernetes manifests
      run: |
        # Update deployment.yaml with correct image
        sed -i "s|gcr.io/YOUR_PROJECT_ID/job-scheduler:latest|${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml
        
        # Update secrets with GitHub secrets
        if [ -n "${{ secrets.JWT_TOKEN }}" ]; then
          JWT_TOKEN_B64=$(echo -n "${{ secrets.JWT_TOKEN }}" | base64)
          sed -i "s|eW91cl9qd3RfdG9rZW5faGVyZQ==|$JWT_TOKEN_B64|g" k8s/secret.yaml
        fi
        
        if [ -n "${{ secrets.AIRCALL_API_TOKEN }}" ]; then
          AIRCALL_TOKEN_B64=$(echo -n "${{ secrets.AIRCALL_API_TOKEN }}" | base64)
          sed -i "s|eW91cl9haXJjYWxsX3Rva2VuX2hlcmU=|$AIRCALL_TOKEN_B64|g" k8s/secret.yaml
        fi
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/network-policy.yaml
        
    - name: Wait for deployment
      run: |
        kubectl wait --for=condition=available --timeout=300s deployment/job-scheduler -n scheduler-app
        
    - name: Verify deployment
      run: |
        kubectl get pods -n scheduler-app
        kubectl get svc -n scheduler-app
        
    - name: Test health endpoint
      run: |
        kubectl exec -n scheduler-app deployment/job-scheduler -- curl -s http://localhost:8081/health

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/v')
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
          --zone ${{ env.GKE_ZONE }} \
          --project ${{ env.PROJECT_ID }}
          
    - name: Update Kubernetes manifests
      run: |
        # Update deployment.yaml with correct image
        sed -i "s|gcr.io/YOUR_PROJECT_ID/job-scheduler:latest|${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}|g" k8s/deployment.yaml
        
        # Update secrets with GitHub secrets
        if [ -n "${{ secrets.JWT_TOKEN }}" ]; then
          JWT_TOKEN_B64=$(echo -n "${{ secrets.JWT_TOKEN }}" | base64)
          sed -i "s|eW91cl9qd3RfdG9rZW5faGVyZQ==|$JWT_TOKEN_B64|g" k8s/secret.yaml
        fi
        
        if [ -n "${{ secrets.AIRCALL_API_TOKEN }}" ]; then
          AIRCALL_TOKEN_B64=$(echo -n "${{ secrets.AIRCALL_API_TOKEN }}" | base64)
          sed -i "s|eW91cl9haXJjYWxsX3Rva2VuX2hlcmU=|$AIRCALL_TOKEN_B64|g" k8s/secret.yaml
        fi
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/network-policy.yaml
        
    - name: Wait for deployment
      run: |
        kubectl wait --for=condition=available --timeout=300s deployment/job-scheduler -n scheduler-app
        
    - name: Verify deployment
      run: |
        kubectl get pods -n scheduler-app
        kubectl get svc -n scheduler-app
        
    - name: Test health endpoint
      run: |
        kubectl exec -n scheduler-app deployment/job-scheduler -- curl -s http://localhost:8081/health
        
    - name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
